input {
  kb_layout = us
  numlock_by_default = true
  repeat_rate = 45
  repeat_delay = 220
  follow_mouse = 1
  follow_mouse_shrink = 8
  focus_on_close = 1
  sensitivity = 0
  accel_profile = adaptive

  touchpad {
    natural_scroll = true
    disable_while_typing = true
    tap-to-click = true
    clickfinger_behavior = true
  }
}

gestures {
  workspace_swipe_distance = 320
  workspace_swipe_forever = true
}
