general {
  gaps_in = 6
  gaps_out = 14
  gaps_workspaces = 10
  border_size = 2
  col.active_border = rgba(22d3eeee) rgba(f472b6ee) rgba(a3e635ee) 45deg
  col.inactive_border = rgba(334155aa)
  resize_on_border = true
  layout = dwindle
  allow_tearing = false
}

dwindle {
  preserve_split = true
  smart_split = true
  smart_resizing = true
  use_active_for_splits = true
}

debug {
  vfr = true
}

render {
  direct_scanout = 2
  new_render_scheduling = true
}

binds {
  workspace_back_and_forth = true
  hide_special_on_workspace_change = true
  focus_preferred_method = 1
}

cursor {
  inactive_timeout = 4
  hide_on_key_press = true
  warp_on_change_workspace = 1
  warp_on_toggle_special = 1
  no_break_fs_vrr = true
  min_refresh_rate = 60
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vrr = 2
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  initial_workspace_tracking = true
}
