# Rofi
windowrulev = float, class:^(rofi)$
windowrulev = center, class:^(rofi)$
windowrulev = size 720 480, class:^(rofi)$
windowrulev = noborder, class:^(rofi)$
windowrulev = opaque, class:^(rofi)$

# Terminales
windowrulev = size 1000 700, class:^(kitty)$, floating:1
windowrulev = float, class:^(scratch-terminal)$
windowrulev = center, class:^(scratch-terminal)$
windowrulev = size 1100 720, class:^(scratch-terminal)$
windowrulev = workspace special:terminal silent, class:^(scratch-terminal)$
windowrulev = opacity 0.96 0.92, class:^(kitty)$

# Navegador y apps principales
windowrulev = opacity 0.98 0.95, class:^(firefox)$
windowrulev = workspace 6 silent, class:^(firefox)$

# Media
windowrulev = workspace 8 silent, class:^(Spotify)$
windowrulev = opacity 0.98 0.94, class:^(Spotify)$

# Capas/paneles
layerrule = blur on, ignore_alpha 0.05, match:namespace gtk4-layer-shell

# Utilidades flotantes
windowrulev = float, title:^(Picture-in-Picture)$
windowrulev = pin, title:^(Picture-in-Picture)$
windowrulev = size 420 240, title:^(Picture-in-Picture)$
windowrulev = move 100%-440 100%-270, title:^(Picture-in-Picture)$
